### Практика №1

In [4]:
# библиотеки
import numpy as np

In [ ]:
# создание массивов
array = np.array([1, 2, 3, 4])

array_zeros = np.zeros((2, 3)) # 2 na 3
array_ones  = np.ones(5) # 1 na 5
array_arange = np.arange(1, 10, 2) # step 2

In [18]:
# Вывод массивов
print(array, array_zeros, array_ones, array_arange, sep="\n")

[1 2 3 4]
[[0. 0. 0.]
 [0. 0. 0.]]
[1. 1. 1. 1. 1.]
[1 3 5 7 9]


In [ ]:
# Вывод атрибутов массивов (размер, тип данных)
print(array_zeros.shape, array_zeros.dtype, sep="\n")


(2, 3)
float64


In [ ]:
# Вывод индексов
print(array[2]) # отдельный элемент (по индексу 2 → значение 3)
print(array[1:4]) # срез подмассива: элементы с 1 по 3 включительно
print(array_zeros[1][2]) #  элемент двумерного массива: 2-я строка и 3-й элемент в этой строке

3
[2 3 4]
0.0


In [ ]:
# Векторные операции и статистики
# создание векторов
x = np.array([1, 2, 3])
y = np.array([10, 20, 30])

# Формирование параметров
sum_xy = x + y          # поэлементное сложение
mul_xy = x * y          # поэлементное умножение
avg = x.mean()          # среднее значение массива x

In [28]:
# Вывод параметров
print(sum_xy, mul_xy, avg, sep="\n")

[11 22 33]
[10 40 90]
2.0


Думаю этого хватит))